const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Tilemap,
		C3.Plugins.progressbar,
		C3.Plugins.Button,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.progressbar.Cnds.CompareProgress,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Player: 0},
	{Lane1: 0},
	{Lane2: 0},
	{Lane3: 0},
	{Touch: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{EnemyHP: 0},
	{MoveTo: 0},
	{Enemy: 0},
	{Pin: 0},
	{txt_EnemyHP: 0},
	{txt_Score: 0},
	{txt_Lives: 0},
	{BaseLine: 0},
	{BtnRetry: 0},
	{ParEnemy: 0},
	{ParPlayer: 0},
	{Audio: 0},
	{BG1: 0},
	{FG1: 0},
	{FG2: 0},
	{FG3: 0},
	{FG4: 0},
	{FG5: 0},
	{Challenge_EnemyHP: 0},
	{Enemy2: 0},
	{CurrentProgress: 0},
	{ProgressBar: 0},
	{TiledBackground: 0},
	{ButtonStart: 0},
	{BG3: 0},
	{BG2: 0},
	{ButtonEnd: 0},
	{FG6: 0},
	{FG7: 0},
	{GameOver1: 0},
	{BGGameOver: 0},
	{txt_FinalScore: 0},
	{Fade: 0},
	{txt_TotalScore: 0},
	{ButtonChallenge: 0},
	{MainMenu1: 0},
	{GameName: 0},
	{MainMenu2: 0},
	{score: 0},
	{lives: 0},
	{feats: 0},
	{difficulty: 0},
	{score_challenge: 0},
	{lives_challenge: 0},
	{difficulty_challenge: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Lane1: class extends self.ITiledBackgroundInstance {},
	Lane2: class extends self.ITiledBackgroundInstance {},
	Lane3: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	txt_EnemyHP: class extends self.ITextInstance {},
	txt_Score: class extends self.ITextInstance {},
	txt_Lives: class extends self.ITextInstance {},
	BaseLine: class extends self.ITiledBackgroundInstance {},
	BtnRetry: class extends self.ISpriteInstance {},
	ParEnemy: class extends self.IParticlesInstance {},
	ParPlayer: class extends self.IParticlesInstance {},
	Audio: class extends self.IInstance {},
	BG1: class extends self.ITilemapInstance {},
	FG1: class extends self.ISpriteInstance {},
	FG2: class extends self.ISpriteInstance {},
	FG3: class extends self.ISpriteInstance {},
	FG4: class extends self.ISpriteInstance {},
	FG5: class extends self.ISpriteInstance {},
	Enemy2: class extends self.ISpriteInstance {},
	ProgressBar: class extends self.IProgressBarInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	ButtonStart: class extends self.IButtonInstance {},
	BG3: class extends self.ITilemapInstance {},
	BG2: class extends self.ITilemapInstance {},
	ButtonEnd: class extends self.IButtonInstance {},
	FG6: class extends self.ISpriteInstance {},
	FG7: class extends self.ISpriteInstance {},
	GameOver1: class extends self.ISpriteInstance {},
	BGGameOver: class extends self.ISpriteInstance {},
	txt_FinalScore: class extends self.ITextInstance {},
	txt_TotalScore: class extends self.ITextInstance {},
	ButtonChallenge: class extends self.IButtonInstance {},
	MainMenu1: class extends self.ISpriteInstance {},
	GameName: class extends self.ISpriteInstance {},
	MainMenu2: class extends self.ISpriteInstance {}
}